### ISSUE TITLE
Some questions & remarks

### ISSUE THREAD

**Issue by cbonami** [dsouzajude/zookeeper-on-aws#2]
Thanks for the great work. I used it and I have a zk cluster running.
Some remarks though:
- the role that needs to be specified, as it will be attached to the zk instances, needs to have the right permissions in order to avoid this "ClientError: An error occurred (AccessDeniedException) when calling the CreateLogStream operation: User: arn:aws:sts::727809097786:assumed-role/BaseIAMRole/i-092437bb95407a400 is not authorized to perform: logs:CreateLogStream on resource: arn:aws:logs:eu-west-1:727809097786:log-group:/zookeeper/instances:log-stream:1" -- can you be specific about the minimum permissions this role needs to have ?
- I cannot tail the zookeeper-logs (user: zookeeper), as I don't have the right permissions ('su -l zookeeper' asks for a password); how can I solve this ?
- Lastly: is there any particular reason why you did not make use of Exhibitor ?

**Comment by dsouzajude** [comment]
Hi @cbonami, thanks for using my zookeeper cluster setup and for opening an issue!

- At a minimum, the role would require the following permissions:
   - logs:CreateLogGroup
   - logs:CreateLogStream
   - logs:PutLogEvents
   - logs:DeleteLogStream
   - logs:DescribeLogStreams
   - ec2:DescribeInstances
   - ec2:DescribeTags
   - ec2:CreateTags
   - autoscaling:Describe*

- The zookeeper user on the instance is not intended to have a password and it is not like any other authenticated user on the system. Typically if you would like to view the logs you would need to use sudo via the root user or any user that has administrative access (`sudo tail -f /var/log/zookeeper/zookeeper.log`). However, i think it would be great if these logs were shipped to a centralized log server or hosting, for example CloudWatchLogs via [awslogs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartEC2Instance.html). Please feel free to submit a PR for that, otherwise i can have a look at it later.

- I haven't worked much with the Exhibitor, but at the time when i was researching about it I felt it was a bit more complicated to setup. I wanted something really simple that just works. Also, i felt i could do a lot more (i.e. autoscale ZK dynamically and autoheal it when there is quorum failure).

Hope this answers your questions!

Also, if you have any suggestions how to improve and make this better, i'd like more comments or you can always open up a PR!

**Comment by dsouzajude** [comment]
Hi @cbonami, I have a PR for addressing your concerns if you're interested in looking at it:

https://github.com/dsouzajude/zookeeper-on-aws/pull/4
